services:
  db:
    image: postgres:15
    container_name: blood_db
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: secret123
      POSTGRES_DB: blooddb
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    restart: unless-stopped

  app:
    build: .
    container_name: blood_app
    ports:
      - "5000:5000"
    environment:
      DB_HOST: db
      DB_NAME: blooddb
      DB_USER: admin
      DB_PASS: secret123
      GROQ_API_KEY: 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
    depends_on:
      - db
    restart: unless-stopped

  nginx:
    image: nginx:alpine
    container_name: blood_nginx
    ports:
      - "8090:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    restart: unless-stopped

  prometheus:
    image: prom/prometheus
    container_name: blood_prometheus
    ports:
      - "9092:9090"
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    restart: unless-stopped

  grafana:
    image: grafana/grafana
    container_name: blood_grafana
    ports:
      - "3000:3000"
    environment:
      GF_SECURITY_ADMIN_USER: admin
      GF_SECURITY_ADMIN_PASSWORD: admin123
    restart: unless-stopped

  node-exporter:
    image: prom/node-exporter
    container_name: blood_node_exporter
    ports:
      - "9101:9100"
    restart: unless-stopped

  jenkins:
    image: jenkins/jenkins:lts
    container_name: blood_jenkins
    ports:
      - "8082:8080"
    volumes:
      - jenkinsdata:/var/jenkins_home
    restart: unless-stopped

volumes:
  pgdata:
  jenkinsdata:
